import type { codingProblems } from '@/lib/db/schema'

type CodingProblemSeed = typeof codingProblems.$inferInsert

// Seed problems for the Debugging module (find and fix the bug) and
// AI-Assisted Coding module (write code with the AI coach). Test cases marked
// hidden are never exposed through the API.
export const codingProblemsSeedData: CodingProblemSeed[] = [
  {
    slug: 'debug-find-max-boundary',
    title: 'Find the Maximum Element (Boundary Bug)',
    statement: [
      'Return the largest value in an integer array.',
      'Input format: First integer n is array size, followed by n space-separated integers.',
      'Output format: Print the single maximum integer.',
      'The starter implementation contains boundary and initialization bugs. Find and fix them.',
    ].join('\n'),
    difficulty: 'easy',
    topic: 'Arrays · Boundary',
    position: 1,
    marks: 10,
    moduleId: null,
    languages: ['c', 'cpp', 'java', 'python', 'javascript'],
    starterCode: {
      c: '// Write code to find maximum element in array\n',
      cpp: '// Write code to find maximum element in array\n',
      java: 'public class Solution {\n    public static void main(String[] args) {\n    }\n}\n',
      python: '# Read input and print maximum element\n',
      javascript: '// Read stdin and print maximum element\n',
    },
    buggyCode: {
      c: [
        '#include <stdio.h>',
        '',
        'int main() {',
        '    int n;',
        '    if (scanf("%d", &n) != 1 || n <= 0) return 0;',
        '    int arr[1000];',
        '    for (int i = 0; i < n; i++) scanf("%d", &arr[i]);',
        '    int max = 0; // BUG: Should initialize with arr[0]',
        '    for (int i = 0; i <= n; i++) { // BUG: <= n causes out-of-bounds',
        '        if (arr[i] > max) max = arr[i];',
        '    }',
        '    printf("%d\\n", max);',
        '    return 0;',
        '}',
      ].join('\n'),
      cpp: [
        '#include <iostream>',
        '#include <vector>',
        'using namespace std;',
        '',
        'int main() {',
        '    int n;',
        '    if (!(cin >> n)) return 0;',
        '    vector<int> arr(n);',
        '    for (int i = 0; i < n; i++) cin >> arr[i];',
        '    int maxVal = 0; // BUG: Should initialize with arr[0]',
        '    for (int i = 0; i <= n; i++) { // BUG: <= n causes out-of-bounds',
        '        if (arr[i] > maxVal) maxVal = arr[i];',
        '    }',
        '    cout << maxVal << endl;',
        '    return 0;',
        '}',
      ].join('\n'),
      java: [
        'import java.util.Scanner;',
        '',
        'public class Solution {',
        '    public static void main(String[] args) {',
        '        Scanner sc = new Scanner(System.in);',
        '        if (!sc.hasNextInt()) return;',
        '        int n = sc.nextInt();',
        '        int[] arr = new int[n];',
        '        for (int i = 0; i < n; i++) arr[i] = sc.nextInt();',
        '        int max = 0; // BUG: Should initialize with arr[0]',
        '        for (int i = 0; i < n; i++) {',
        '            if (arr[i] > max) max = arr[i];',
        '        }',
        '        System.out.println(max);',
        '    }',
        '}',
      ].join('\n'),
      python: [
        'import sys',
        '',
        'def main():',
        '    data = sys.stdin.read().split()',
        '    if not data:',
        '        return',
        '    n = int(data[0])',
        '    nums = [int(x) for x in data[1:n+1]]',
        '    max_val = 0  # BUG: Should initialize with nums[0]',
        '    for i in range(len(nums)):',
        '        if nums[i] > max_val:',
        '            max_val = nums[i]',
        '    print(max_val)',
        '',
        'main()',
      ].join('\n'),
      javascript: [
        'const fs = require("fs");',
        '',
        'function main() {',
        '    const input = fs.readFileSync(0, "utf-8").trim().split(/\\s+/);',
        '    if (!input || input.length < 2) return;',
        '    const n = parseInt(input[0], 10);',
        '    const nums = input.slice(1, n + 1).map(Number);',
        '    let max = 0; // BUG: Should initialize with nums[0]',
        '    for (let i = 0; i < nums.length; i++) {',
        '        if (nums[i] > max) max = nums[i];',
        '    }',
        '    console.log(max);',
        '}',
        '',
        'main();',
      ].join('\n'),
    },
    testCases: [
      { name: 'Test 1', stdin: '5\n3 8 2 15 6\n', expectedOutput: '15', hidden: false },
      { name: 'Test 2', stdin: '4\n1 2 8 4\n', expectedOutput: '8', hidden: false },
      { name: 'Test 3 (Negative numbers)', stdin: '3\n-10 -4 -20\n', expectedOutput: '-4', hidden: true },
      { name: 'Test 4 (Single element)', stdin: '1\n42\n', expectedOutput: '42', hidden: true },
    ],
    explanation: 'Initialize max with the first array element arr[0] instead of 0 (to handle negative values), and ensure loop boundary stops at i < n.',
  },
  {
    slug: 'debug-two-sum-off-by-one',
    title: 'Fix the Off-By-One: Pair Sum',
    statement: [
      'The function below should read a target sum and a list of integers, then print',
      'the first pair of indices (i < j) whose values add up to the target, formatted as "i j".',
      'It currently prints an incorrect pair or compares an element with itself. Find and fix the bug.',
      'Input format: First line is target sum, second line is space-separated integers.',
    ].join('\n'),
    difficulty: 'easy',
    topic: 'Arrays · Iteration',
    position: 2,
    marks: 10,
    moduleId: null,
    languages: ['python', 'c', 'cpp', 'java', 'javascript'],
    starterCode: {
      python: '# Read input, find the pair, print "i j"\n',
    },
    buggyCode: {
      python: [
        'import sys',
        '',
        'def main():',
        '    data = sys.stdin.read().split()',
        '    target = int(data[0])',
        '    nums = [int(x) for x in data[1:]]',
        '    for i in range(len(nums)):',
        '        for j in range(i, len(nums)):  # BUG: should be i+1',
        '            if nums[i] + nums[j] == target:',
        '                print(i, j)',
        '                return',
        '    print("-1 -1")',
        '',
        'main()',
      ].join('\n'),
    },
    testCases: [
      { name: 'basic', stdin: '9\n2 7 11 15\n', expectedOutput: '0 1', hidden: false },
      { name: 'middle-pair', stdin: '10\n1 3 5 7 9\n', expectedOutput: '1 3', hidden: false },
      { name: 'no-pair', stdin: '100\n1 2 3\n', expectedOutput: '-1 -1', hidden: true },
      { name: 'duplicate-values', stdin: '6\n3 3 4\n', expectedOutput: '0 1', hidden: true },
    ],
    explanation: 'The inner loop starts at j = i, comparing an element with itself. Start at j = i + 1 so every pair has two distinct indices.',
  },
  {
    slug: 'debug-fizzbuzz-modulo',
    title: 'Fix the Modulo Bug: FizzBuzz Report',
    statement: [
      'This program should print, for n numbers on the second line, either the number,',
      '"Fizz" (divisible by 3), "Buzz" (divisible by 5), or "FizzBuzz" (divisible by both),',
      'one result per line. It currently misclassifies numbers divisible by both 3 and 5. Fix it.',
    ].join('\n'),
    difficulty: 'easy',
    topic: 'Control Flow · Modulo',
    position: 3,
    marks: 10,
    moduleId: null,
    languages: ['python', 'cpp', 'java', 'javascript'],
    starterCode: { python: '# Print FizzBuzz style output, one line per number\n' },
    buggyCode: {
      python: [
        'import sys',
        '',
        'def main():',
        '    data = sys.stdin.read().split()',
        '    for token in data[1:]:',
        '        n = int(token)',
        '        if n % 3 == 0:',
        '            print("Fizz")  # BUG: misses the divisible-by-15 case',
        '        elif n % 5 == 0:',
        '            print("Buzz")',
        '        else:',
        '            print(n)',
        '',
        'main()',
      ].join('\n'),
    },
    testCases: [
      { name: 'mixed', stdin: '0\n3 5 15 7\n', expectedOutput: 'Fizz\nBuzz\nFizzBuzz\n7', hidden: false },
      { name: 'fifteens', stdin: '0\n30 45\n', expectedOutput: 'FizzBuzz\nFizzBuzz', hidden: true },
    ],
    explanation: 'Check the divisible-by-both case first (n % 15 == 0) before the single-divisor cases.',
  },
]
